### ISSUE TITLE
Upgrade to Crystal v0.36.x

### ISSUE THREAD

**Issue by lbarasti** [crystal-data/num.cr#63]
#### Problem description

The latest version of `alea` is pulled in as a dependency by `num.cr`. `alea`'s latest now [requires Crystal v0.36.0 or greater](https://github.com/nin93/alea/commits/master)). This forces `num.cr` users to move to v0.36.x, as far as I can tell.

It seems Crystal 0.36.1 complains about
1. the declaration of the abstract method `abstract def cache` in `Num::Grad::Gate(T)`
2. the fact that `Indexable.range_to_index_and_count` now can return `nil`

I've opened a reference PR to discuss the details of this: https://github.com/crystal-data/num.cr/pull/64

**Comment by christopherzimmerman** [comment]
Crystal 1.0.0 is now supported on the master branch, this can now be closed.
